### ISSUE TITLE
add: printColorList() function 

### ISSUE THREAD

**Issue by Riaaggarwal06** [IEEE-VIT/spectra#11]
Create an algorithm that prints all the colours that have been detected.

**Comment by SilverDragonOfR** [comment]
@Riaaggarwal06 I have made a PR for this issue.

**Comment by SilverDragonOfR** [comment]
@Riaaggarwal06 Merged and made necessary changes.
I have opened another PR for this issue.

**Comment by Riaaggarwal06** [comment]
Well done! @SilverDragonOfR
